name: square_progress_bar
description: A square progress bar.
version: 1.0.0
homepage: https://github.com/yasirdx777/DXProgressBar

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter: