name: square_progress_bar
description: A square progress bar that you can use easily, Just provide the progress in a range from 0.0 to 1.0 and you are set to go.
version: 1.1.1
homepage: https://github.com/yasirdx777/square_progress_bar

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter: